import pandas as pd
import json
from pathlib import Path
from geopy.distance import geodesic
from datetime import datetime, timedelta

# --- Configuration ---
# Input files generated by simulate_entities.py
SIMULATION_DIR = Path("../data/simulation_output")
ACCOUNT_DETAILS_FILE = SIMULATION_DIR / "simulated_account_details.json"
TRANSACTIONS_FILE = SIMULATION_DIR / "simulated_account_transactions.csv"



